accounts/urls.py
from django.urls import path
from .import views

urlpatterns=[
     path('',views.index, name='index'),
     path('register/',views.register, name='register'),
     path('student_register/',views.student_register.as_view(), name='student_register'),
     path('warden_register/',views.warden_register.as_view(), name='warden_register'),
     path('login/',views.login_request, name='login'),
     path('logout/',views.logout_view, name='logout'),
     path('student_land/',views.student_land, name='student_land'),
     path('warden_land/',views.warden_land, name='warden_land'),
     # -----------------other link--------------------
     #the line below I added to make warden login work for some views like add dues - error message below:
     #Reverse for 'warden_login' not found. 'warden_login' is not a valid view function or pattern name
     path('login/',views.login_request, name='warden_login'),
     #end of line added for warden_login
     path('warden_dues/', views.warden_dues, name='warden_dues'),
     path('warden_add_due/', views.warden_add_due, name='warden_add_due'),
     path('warden_remove_due/', views.warden_remove_due, name='warden_remove_due'),
     path('warden_student_list/', views.warden_student_list, name='warden_student_list'),
     path('warden_student_list/change_student_details/<slug:enrollment_no>', views.change_student_details, name='change_student_details'),
     path('warden_student_list/clear_room_details/<slug:enrollment_no>', views.clear_room_details, name='clear_room_details'),
     path('hostels/<slug:hostel_name>/', views.hostel_detail_view, name='hostel'),
     path('login/edit/', views.edit, name='edit'),
     path('login/select/', views.select, name='select'),
     path('register/login/edit/', views.edit, name='update'),
     path('login/edit/', views.edit, name='profile'),
]

hostelproject/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('accounts/', include('accounts.urls')),
    path('', include('accounts.urls')),
    path('whatilike123/', admin.site.urls),
]  + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

# if settings.DEBUG:
#     urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
#      + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

accounts/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser


class User(AbstractUser):
    first_name = models.CharField(max_length=200, null=True)
    last_name = models.CharField(max_length=200, null=True)
    is_student = models.BooleanField(default=False)
    is_warden = models.BooleanField(default=False)


class Student(models.Model):
    user = models.OneToOneField(
        User,
        default=None,
        null=True,
        on_delete=models.CASCADE)
    gender_choices = [('M', 'Male'), ('F', 'Female')]
    enrollment_no = models.CharField(max_length=5, unique=True, default=1000, null=False)
    course = models.ForeignKey(
        'Course',
        null=True,
        default=None,
        on_delete=models.CASCADE)
    dob = models.DateField(
        max_length=10,
        help_text="format : YYYY-MM-DD",
        null=True)
    gender = models.CharField(
        choices=gender_choices,
        max_length=1,
        default=None,
        null=True)
    room = models.OneToOneField(
        'Room',
        blank=True,
        on_delete=models.CASCADE,
        null=True)
    room_allotted = models.BooleanField(default=False)
    no_dues = models.BooleanField(default=True)

    def __str__(self):
        return self.enrollment_no

class Room(models.Model):
    room_choice = [('S', 'Single Occupancy'), ('D', 'Double Occupancy'), ('P', 'Reserved for Research Scholars'),('B', 'Both Single and Double Occupancy')]
    no = models.CharField(max_length=6)
    name = models.CharField(max_length=10)
    room_type = models.CharField(choices=room_choice, max_length=1, default=None)
    vacant = models.BooleanField(default=False)
    hostel = models.ForeignKey('Hostel', on_delete=models.CASCADE)

    def __str__(self):
        return self.name + '' + self.room_type + ' in ' + self.hostel.name


class Hostel(models.Model):
    name = models.CharField(max_length=10)
    gender_choices = [('M', 'Male'), ('F', 'Female')]
    gender = models.CharField(
        choices=gender_choices,
        max_length=1,
        default=None,
        null=True)
    course = models.ManyToManyField('Course', default=None, blank=True)
    caretaker = models.CharField(max_length=100, blank=True)

    def __str__(self):
        return self.name


class Course(models.Model):
    # if a student has enrollment number iit2017001 then the course code is iit2017
    code = models.CharField(max_length=100, default=None)
    room_choice = [('S', 'Single Occupancy'), ('D', 'Double Occupancy'), ('P', 'Reserved for Research Scholars'), ('B', 'Both Single and Double Occupancy')]
    room_type = models.CharField(choices=room_choice, max_length=1, default='D')

    def __str__(self):
        return self.code


class Warden(models.Model):
    user = models.OneToOneField(
        User,
        default=None,
        null=True,
        on_delete=models.CASCADE)
    hostel = models.ForeignKey('Hostel',
        default=None,
        null=True,
        on_delete=models.CASCADE)

    def __str__(self):
        return self.user.first_name

templates/add_due.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}

{% block content %}

<div class="wrap">
  <div class="col col-8 offset-2 mt-5">
    <form action="" method="post">
        {% csrf_token %}
      <div class="fields">{{ form|crispy }}</div>
      <br>
      <input class="btn btn-block btn-danger" type="submit" value="ADD DUE">
    </form>
    </div>
  </div>
{% endblock content %}

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="utf-8">
  <meta content="width=device-width, initial-scale=1.0" name="viewport">

  <title>Dormitory</title>
  <meta content="" name="description">
  <meta content="" name="keywords">

  <!-- Favicons -->
  <link href="{% static 'landing/assets/img/favicon.png' %}" rel="icon">
  <link href="{% static 'landing/assets/img/apple-touch-icon.png' %}" rel="apple-touch-icon">

  <!-- Google Fonts -->
  <link href="https://fonts.googleapis.com/css?family=Open+Sans:300,300i,400,400i,600,600i,700,700i|Roboto:300,300i,400,400i,500,500i,600,600i,700,700i|Poppins:300,300i,400,400i,500,500i,600,600i,700,700i" rel="stylesheet">

  <!-- Vendor CSS Files -->
  <link href="{% static 'landing/assets/vendor/aos/aos.css' %}" rel="stylesheet">
  <link href="{% static 'landing/assets/vendor/bootstrap/css/bootstrap.min.css' %}" rel="stylesheet">
  <link href="{% static 'landing/assets/vendor/bootstrap-icons/bootstrap-icons.css' %}" rel="stylesheet">
  <link href="{% static 'landing/assets/vendor/boxicons/css/boxicons.min.css' %}" rel="stylesheet">
  <link href="{% static 'landing/assets/vendor/glightbox/css/glightbox.min.css' %}" rel="stylesheet">
  <link href="{% static 'landing/assets/vendor/swiper/swiper-bundle.min.css' %}" rel="stylesheet">

  <!-- Template Main CSS File -->
  <link href="{% static 'landing/assets/css/style.css' %}" rel="stylesheet">

  <!-- =======================================================
  * Author: BootstrapMade.com
  * License: https://bootstrapmade.com/license/
  ======================================================== -->
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.14.0/css/all.min.css">

          <!-- yatranslate -->
          <script src="{% static 'translate/js/yatranslate.js' %}"></script>
          <link rel="stylesheet" href="{% static 'translate/css/yatranslate.css' %}">
          <!-- END yatranslate -->
</head>

<body>

  <!-- ======= Top Bar ======= -->
  <section id="topbar" class="d-flex align-items-center">
    <div class="container d-flex justify-content-center justify-content-md-between">
      <div class="contact-info d-flex align-items-center">
        <i class="bi bi-envelope d-flex align-items-center"><a href="mailto:oooladeleodewole@gmail.com">dormitory@gmail.com</a></i>
        <i class="bi bi-phone d-flex align-items-center ms-4"><span>+90 533 847 ****</span></i>
      </div>
      <div class="social-links d-none d-md-flex align-items-center">
        <a href="#" class="twitter"><i class="bi bi-twitter"></i></a>
        <a href="#" class="facebook"><i class="bi bi-facebook"></i></a>
        <a href="#" class="instagram"><i class="bi bi-instagram"></i></a>
        <a href="#" class="linkedin"><i class="bi bi-linkedin"></i></i></a>
        
      </div>
    </div>
  </section>

  <!-- ======= Header ======= -->
  <header id="header" class="d-flex align-items-center">
    <div class="container d-flex align-items-center justify-content-between">

      <h1 class="logo"><a href="/">Dormitory Portal<span>.</span></a></h1>
      <!-- Uncomment below if you prefer to use an image logo -->
      <!-- <a href="index.html" class="logo"><img src="assets/img/logo.png" alt=""></a>-->

      <nav id="navbar" class="navbar">
        <ul>
          <li><a class="nav-link scrollto active" href="/">Home</a></li>


          {% if not request.user.is_authenticated %}

          <li><a class="nav-link scrollto"  href="{% url 'register' %}">Register</a> </li>
          {% endif %}

            {% if request.user.is_authenticated and request.user.is_student %}
            <li><a class="nav-link scrollto"  href="{% url 'edit' %}">Update Details</a> </li>
            <li><a class="nav-link scrollto" href="{% url 'select' %}">Select a Room</a> </li>
            {% endif %}

            {% if request.user.is_authenticated and request.user.is_warden %}

            <li><a class="nav-link scrollto" href="{% url 'warden_dues' %}">Dues</a> </li>
            <li><a class="nav-link scrollto"  href="{% url 'warden_add_due' %}">Add Due</a> </li>
            <li><a class="nav-link scrollto" href="{% url 'warden_remove_due' %}">Remove Due</a> </li>
            <li><a class="nav-link scrollto"  href="{% url 'warden_student_list' %}">List Students</a> </li>
            {% endif %}
            {% if request.user.is_authenticated %}
            <li><a href="{% url 'logout' %}"><button class="btn btn-success"><i class="fa fa-user"></i> {{ user }} | Logout </button></a></li>
            {% else %}
            <li><a href="{% url 'login' %}"><button class="btn btn-info">  Login <i class="fas fa-sign-in-alt"></i></button></a></li>
            {% endif %}
            {% include 'translate.html' %} 
          </ul>
          <i class="bi bi-list mobile-nav-toggle"></i>
        <!-- yatranslate --------------------------->
        <div class="social-links d-none d-md-flex align-items-center">
        
      </div>
          <!------------- End Ya_translate------------------------------ -->
<!-- <li class="dropdown"><a href="#"><span>Drop Down</span> <i class="bi bi-chevron-down"></i></a>
            <ul>
              <li><a href="#">Drop Down 1</a></li>
              <li class="dropdown"><a href="#"><span>Deep Drop Down</span> <i class="bi bi-chevron-right"></i></a>
                <ul>
                  <li><a href="#">Deep Drop Down 1</a></li>
                  <li><a href="#">Deep Drop Down 2</a></li>
                  <li><a href="#">Deep Drop Down 3</a></li>
                  <li><a href="#">Deep Drop Down 4</a></li>
                  <li><a href="#">Deep Drop Down 5</a></li>
                </ul>
              </li>
              <li><a href="#">Drop Down 2</a></li>
              <li><a href="#">Drop Down 3</a></li>
              <li><a href="#">Drop Down 4</a></li>
            </ul>
          </li> -->
        
      </nav><!-- .navbar -->

    </div>
  </header><!-- End Header -->


  <main class="container">
  <style>
	#footer {
	  position: fixed;
	  bottom: 0;
	  width: 100%;
	}
	#footer .footer-top {
       padding: 0px 0 0px 0;
       background: #000;
}
</style>
    {% block content %}
    {% endblock content %}

  </main><!-- End #main -->

  <!-- ======= Footer ======= -->
  <footer id="footer">


    <div class="footer-top">
      <div class="container">
      </div>
    </div>

    <div class="container py-4">
      <div class="copyright">
        &copy; Copyright <strong><span>Dormitory</span></strong>. All Rights Reserved
      </div>
      <div class="credits">
        <!-- All the links in the footer should remain intact. -->
        <!-- You can delete the links only if you purchased the pro version. -->
        <!-- Licensing information: https://bootstrapmade.com/license/ -->
      
        Designed by <a href="https://bootstrapmade.com/">BootstrapMade</a>
      </div>
    </div>
  </footer><!-- End Footer -->

  <div id="preloader"></div>
  <a href="#" class="back-to-top d-flex align-items-center justify-content-center"><i class="bi bi-arrow-up-short"></i></a>

  <!-- Vendor JS Files -->
  <script src="{% static 'landing/assets/vendor/purecounter/purecounter.js' %}"></script>
  <script src="{% static 'landing/assets/vendor/aos/aos.js' %}"></script>
  <script src="{% static 'landing/assets/vendor/bootstrap/js/bootstrap.bundle.min.js' %}"></script>
  <script src="{% static 'landing/assets/vendor/glightbox/js/glightbox.min.js' %}"></script>
  <script src="{% static 'landing/assets/vendor/isotope-layout/isotope.pkgd.min.js' %}"></script>
  <script src="{% static 'landing/assets/vendor/swiper/swiper-bundle.min.js' %}"></script>
  <script src="{% static 'landing/assets/vendor/waypoints/noframework.waypoints.js' %}"></script>
  <script src="{% static 'landing/assets/vendor/php-email-form/validate.js' %}"></script>

  <!-- Template Main JS File -->
  <script src="{% static 'landing/assets/js/main.js' %}"></script>
    <!-- Hide footer on scroll-->
  <script>
  window.addEventListener('scroll', function() {

  var footer = document.getElementById('footer');

  var scrollPosition = window.pageYOffset || document.documentElement.scrollTop;

  if ((scrollPosition + window.innerHeight) >= document.documentElement.scrollHeight) {

    footer.style.display = 'none';

  } else {

    footer.style.display = 'block';

  }

});
  </script>
        {% block scripts %}
        {% endblock %}

</body>

</html>

templates/hostels.html
{% extends 'base.html' %}

{% block content %}

<!--<h4 class = "text-uppercase"> {{ hostel.name }} ROOM LIST </h4>-->

<div class="display_table">
 	<table class="table table-striped">
		<thead class="table-danger">
          <tr>
            <th>COUNT</th>
            <th>ROOM NO</th>
            <th>ROOM ID</th>
            <th>ROOM TYPE</th>
            <th>DORMITORY</th>
            <th>STATUS</th>
          </tr>
        </thead>
      {% for room in rooms %}
          <tr>
            <td>{{forloop.counter}}</td>
            <td>{{ room.no }}</td>
            <td>{{ room.name }}</td>
            <td> {{ room.room_type }}</td>
            <td> {{ hostel.name }}</td>
            <td style="{% if not room.vacant %} color: red {% else %} color: green {% endif %}"> {% if room.vacant %} vacant {% else %} occupied {% endif %} </td>
          </tr>
      {% endfor %}
    </table>
</div>



{% endblock content %}

templates/index.html
<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="Mark Otto, Jacob Thornton, and Bootstrap contributors">
    <meta name="generator" content="Hugo 0.79.0">
    <title>My Title</title>

    <link rel="canonical" href="https://getbootstrap.com/docs/5.0/examples/navbar-fixed/">



    <!-- Bootstrap core CSS -->
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">

    <!-- Favicons -->
<!--<link rel="apple-touch-icon" href="/docs/5.0/assets/img/favicons/apple-touch-icon.png" sizes="180x180">-->
<!--<link rel="icon" href="/docs/5.0/assets/img/favicons/favicon-32x32.png" sizes="32x32" type="image/png">-->
<!--<link rel="icon" href="/docs/5.0/assets/img/favicons/favicon-16x16.png" sizes="16x16" type="image/png">-->
<!--<link rel="manifest" href="/docs/5.0/assets/img/favicons/manifest.json">-->
<!--<link rel="mask-icon" href="/docs/5.0/assets/img/favicons/safari-pinned-tab.svg" color="#7952b3">-->
<!--<link rel="icon" href="/docs/5.0/assets/img/favicons/favicon.ico">-->
<meta name="theme-color" content="#7952b3">


    <style>
      .bd-placeholder-img {
        font-size: 1.125rem;
        text-anchor: middle;
        -webkit-user-select: none;
        -moz-user-select: none;
        user-select: none;
      }
      @media (min-width: 768px) {
        .bd-placeholder-img-lg {
          font-size: 3.5rem;
        }
      }
    </style>


    <!-- Custom styles for this template -->
<!--    <link href="navbar-top-fixed.css" rel="stylesheet">-->
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.14.0/css/all.min.css">
  </head>
  <body>


<main class="container">
  <div class="bg-light p-5 rounded">

{% if not user.is_authenticated %}
    <br>
<div class="text-center"><h4>Welcome to Dormitory Management System</h4></div>
<br>
<div class="row">
  <div class="col-sm-6">
    <div class="card">
      <div class="card-body">
        <h5 class="card-title">Europe Users</h5>
        <p class="card-text">Click here if you are accessing this Website from Within Europe.    .</p>
          <a href="{% url 'register' %}" class="btn btn-warning">Click Here</a>
      </div>
    </div>
  </div>
  <div class="col-sm-6">
    <div class="card">
      <div class="card-body">
        <h5 class="card-title">Non Europe Users</h5>
        <p class="card-text">Click here if you are accessing this Website from Outside Europe.</p>
        <a href="{% url 'register' %}" class="btn btn-danger">Click here </a>
      </div>
    </div>
  </div>
</div>
{% else %}
<h4> Welcome to Dormitory Management  </h4>
<h6> Click here to Logout  <a href="{% url 'logout' %}">Logout</a> </h6>
{% endif %}

    </div>
</div>

  </div>
</main>

  </body>
<script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
</html>

templates/login.html
{% extends 'base.html' %}
{% load widget_tweaks %}
{% block content %}

    <section>
        <div class="container">
          <div class="row">
            <div class="col-md-6 mx-auto">
              <div class="card">
                <div class="card-header text-black">
                  <h2>Login</h2>
                </div>
                <div class="card-body">
                    <form action="{% url 'login' %}" method="POST" novalidate>
                      {% csrf_token %}
                         {% for field in form.visible_fields %}
                           <div class="form-group">
                               {{ field.label_tag }}
                                  {% render_field field class="form-control" %}
                                    {% if messages%}
                                      {% for message in messages %}
                                        <span style="color:red">{{ message }}</span>
                                      {% endfor %}
                                     {% endif %}
                         {% endfor %}
                         <br>
                             <input type="submit" value="Login" class="btn btn-block btn-primary">
                           </div>
                    </form>
                 </div>
                    </div>   
                </div>
              </div>
            </div>
        </div>
      </section>

{% endblock content %}

templates/select_room.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}

{% block content %}
<div class="wrap">
<div class="col col-8 offset-2 mt-5">
    {% if not user.student.room %}
<div class="alert alert-danger" role="alert">
 <h4> Make Sure You Update your Profile before selecting a Room!</h4>
    <h5 >Room Categories:</h5>
    <p class = "text-danger">S = Single Occupancy</p>
    <p class = "text-danger">D = Double Occupancy </p>
    <p class = "text-danger">B = Both Single and Double Occupancy</p>
    <p class = "text-danger">P = Reserved for Research Scholars</p>
</div>
{% endif %}
    <form action="" method="post">
        {% csrf_token %}
         {{form|crispy}}
    <br>
      <input class="btn btn-primary" type="submit" value="UPDATE">
    </form>
  </div>
</div>  
  <link href="https://cdn.jsdelivr.net/npm/select2@4.1.0-rc.0/dist/css/select2.min.css" rel="stylesheet" />
{% endblock content %}


{% block scripts %}
<script src="https://code.jquery.com/jquery-3.3.1.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/select2@4.1.0-rc.0/dist/js/select2.min.js"></script>
<script>
  $(document).ready(function() {
    $('#id_room').select2({
      dropdownAutoWidth : true,
      allowClear: true,
      placeholder: "Please select a room",

    });
});
</script>
{% endblock %}

templates/student_land.html
<h1>Welcome Student {{user.username}}</h1>


{% if user.is_student %}
<a href="{% url 'logout' %}">Logout</a> <br>
<br>
<a href="{% url 'edit' %}"> Update Details</a>
<br>
<a href="{% url 'select' %}"> Select a Room</a>
<br>
{% else %}
<a href="{% url 'register' %}">Register</a> <br>
<br>
<a href="{% url 'login' %}">Login</a>
<br>
<br>
<br>
{% endif %}


{% if user.is_warden %}
<a href="{% url 'logout' %}">Logout</a> <br>
<br>
<a href="{% url 'warden_dues' %}"> Dues </a>
<br>
<a href="{% url 'warden_add_due' %}"> Add Due </a>
<br>
<a href="{% url 'warden_remove_due' %}">  Remove Due </a>
<br>
<a href="{% url 'login' %}"> List Rooms </a>
<br>
<a href="{% url 'warden_student_list' %}"> List Students </a>
<br>
{% else %}
<a href="{% url 'register' %}">Register</a> <br>
<br>
<a href="{% url 'login' %}">Login</a>
{% endif %}

templates/student_register.html
{% extends 'base.html' %}
{% load widget_tweaks %}
{% load crispy_forms_tags %}
{% block content %}

    <section>
        <div class="container">
          <div class="row">
            <div class="col-md-6 mx-auto">
              <div class="card">
                <div class="card-header text-black">
                  <h2>Student Registration</h2>
                </div>
                <div class="card-body">
                    <form action="{% url 'student_register' %}" method="POST" novalidate>
                      {% csrf_token %}
                        {{form|crispy}}
<!--                         {% for field in form.visible_fields %}-->
<!--                           <div class="form-group">-->
<!--                               {{ field.label_tag }}-->
<!--                                  {% render_field field class="form-control" %}-->
<!--                                    {% for error in field.errors %}-->
<!--                                      <span style="color:red">{{ error }}</span>-->
<!--                                    {% endfor %}-->
<!--                         {% endfor %}-->
                             <input type="submit" value="Register" class="btn btn-block btn-primary">
                           </div>
                    </form>
                 </div>
                    </div>   
                </div>
              </div>
            </div>
        </div>
      </section>

{% endblock content %}

templates/translate.html
{% load static %}
<!-- yatranslate --------------------------->
            <div class="lang lang_fixed">
              <div id="ytWidget" style="display: none;"></div>
              <div class="lang__link lang__link_select" data-lang-active="en">
                  <img class="lang__img lang__img_select" src="{% static 'translate/images/lang/lang__en.png' %}" alt="en">
              </div>
              <div class="lang__list" data-lang-list="">
                  <a class="lang__link lang__link_sub" data-ya-lang="ru">
                      <img class="lang__img" src="{% static 'translate/images/lang/lang__ru.png' %}" alt="ru">
                      Russian
                  </a>
                  <a class="lang__link lang__link_sub" data-ya-lang="en">
                      <img class="lang__img" src="{% static 'translate/images/lang/lang__en.png' %}" alt="en">
                      English
                  </a>
                  <a class="lang__link lang__link_sub" data-ya-lang="de">
                      <img class="lang__img" src="{% static 'translate/images/lang/lang__de.png' %}" alt="de">
                      German
                  </a>
                  <a class="lang__link lang__link_sub" data-ya-lang="zh">
                      <img class="lang__img" src="{% static 'translate/images/lang/lang__zh.png' %}" alt="zh">
                    Chinese
                    </a>
                  <a class="lang__link lang__link_sub" data-ya-lang="ar">
                    <img class="lang__img" src="{% static 'translate/images/lang/lang__ar.png' %}" alt="ar">
                    Arabic
                </a>
                  <a class="lang__link lang__link_sub" data-ya-lang="fr">
                      <img class="lang__img" src="{% static 'translate/images/lang/lang__fr.png' %}" alt="fr">
                    French  
                  </a>
                  <a class="lang__link lang__link_sub" data-ya-lang="el">
                      <img class="lang__img" src="{% static 'translate/images/lang/lang__el.png' %}" alt="el">
                    Greek
                    </a>
              </div>
          </div>
      
          <!------------- End Ya_translate------------------------------ -->

templates/warden_land.html
<h1>Welcome Warden {{user.username}}</h1>


{% if user.is_student %}
<a href="{% url 'logout' %}">Logout</a> <br>
<br>
<a href="{% url 'edit' %}"> Update Details</a>
<br>
<a href="{% url 'select' %}"> Select a Room</a>
<br>
{% else %}
<a href="{% url 'register' %}">Register</a> <br>
<br>
<a href="{% url 'login' %}">Login</a>
<br>
<br>
<br>
{% endif %}


{% if user.is_warden %}
<a href="{% url 'logout' %}">Logout</a> <br>
<br>
<a href="{% url 'warden_dues' %}"> Dues </a>
<br>
<a href="{% url 'warden_add_due' %}"> Add Due </a>
<br>
<a href="{% url 'warden_remove_due' %}">  Remove Due </a>
<br>
<a href="{% url 'login' %}"> List Rooms </a>
<br>
<a href="{% url 'warden_student_list' %}"> List Students </a>
<br>
{% else %}
<a href="{% url 'register' %}">Register</a> <br>
<br>
<a href="{% url 'login' %}">Login</a>
{% endif %}